const canvas=document.querySelector("#sky"),ctx=canvas.getContext("2d",{alpha:false});let scene=null,showG=true,showF=false,showA=false;
let yaw=.55,pitch=.28,zoom=1.7,drag=null,showS=false;\nconst shellRadii=[50,100,160,200,300];\nconst anchors=[\n {id:"origin",label:"Milky Way / observer",position:[0,0,0],status:"reference"},\n {id:"laniakea",label:"Laniakea centre",position:[-47,13,-5],status:"published CF reconstruction",source:"Sorce et al. constrained Local Universe simulations"},\n {id:"great-attractor",label:"Great Attractor",position:[-40,5,0],status:"CF4/WALLABY reconstruction",source:"WALLABY pilot + CF4"},\n {id:"vela",label:"Vela",position:[-130,40,-140],status:"CF4/WALLABY reconstruction",source:"WALLABY pilot + CF4"}\n];
const demo={coordinateFrame:{coordinates:"supergalactic",units:"Mpc/h"},layers:[{id:"galaxies",data:Array.from({length:900},(_,i)=>{const a=i*2.399963,r=25+240*Math.sqrt((i+.5)/900),z=55*Math.sin(i*.37)*(1-r/320);return{id:"preview-"+i,position:[r*Math.cos(a),r*Math.sin(a),z],basin_id:i%7}})},{id:"streamlines",data:[]}]};
function resize(){const d=Math.min(devicePixelRatio||1,2);canvas.width=innerWidth*d;canvas.height=innerHeight*d;ctx.setTransform(d,0,0,d,0,0)}addEventListener("resize",resize);resize();
function project(p){let[x,y,z]=p;const cy=Math.cos(yaw),sy=Math.sin(yaw);[x,y]=[x*cy-y*sy,x*sy+y*cy];const cp=Math.cos(pitch),sp=Math.sin(pitch);[y,z]=[y*cp-z*sp,y*sp+z*cp];const s=Math.min(innerWidth,innerHeight)*.00145*zoom;return[innerWidth/2+x*s,innerHeight/2-z*s,y]}
function draw(){ctx.fillStyle="#02040a";ctx.fillRect(0,0,innerWidth,innerHeight);if(!scene)return;const g=scene.layers.find(x=>x.id==="galaxies")?.data||[],f=scene.layers.find(x=>x.id==="streamlines")?.data||[];
if(showS){ctx.strokeStyle="#ffffff18";ctx.lineWidth=.7;for(const r of shellRadii){ctx.beginPath();for(let i=0;i<=96;i++){const a=i/96*Math.PI*2,q=project([r*Math.cos(a),r*Math.sin(a),0]);i?ctx.lineTo(q[0],q[1]):ctx.moveTo(q[0],q[1])}ctx.stroke();const lab=project([r,0,0]);ctx.fillStyle="#ffffff55";ctx.font="9px system-ui";ctx.fillText(r+" h⁻¹ Mpc",lab[0]+3,lab[1]);}}\nif(showA){ctx.strokeStyle="#ffffff22";for(const p of [[[0,0,0],[260,0,0]],[[0,0,0],[0,260,0]],[[0,0,0],[0,0,260]]]){const a=project(p[0]),b=project(p[1]);ctx.beginPath();ctx.moveTo(a[0],a[1]);ctx.lineTo(b[0],b[1]);ctx.stroke()}}
if(showF){ctx.strokeStyle="#7aa7ff38";ctx.lineWidth=.7;for(const l of f){ctx.beginPath();l.points.forEach((p,i)=>{const q=project(p);i?ctx.lineTo(q[0],q[1]):ctx.moveTo(q[0],q[1])});ctx.stroke()}}
if(showG){for(const o of g){const q=project(o.position);const alpha=Math.max(.18,1-Math.abs(q[2])/700);ctx.fillStyle=`rgba(225,235,255,${alpha})`;ctx.fillRect(q[0],q[1],1.35,1.35)}}\nctx.font="11px system-ui";ctx.textBaseline="middle";for(const a of anchors){const q=project(a.position);ctx.fillStyle="#fff";ctx.beginPath();ctx.arc(q[0],q[1],a.id==="origin"?3:2,0,Math.PI*2);ctx.fill();ctx.fillStyle="#d9e5ff";ctx.fillText(a.label,q[0]+6,q[1]);}\nrequestAnimationFrame(draw)}requestAnimationFrame(draw);
async function load(){try{const r=await fetch("../data/cf4/scene-mobile.json",{cache:"no-store"});if(!r.ok)throw 0;scene=await r.json();document.querySelector("#status").textContent=`${scene.layers[0].count.toLocaleString()} galaxies · ${scene.layers[1].count.toLocaleString()} flows`;document.querySelector("#scale").textContent=`Supergalactic · ${scene.coordinateFrame.units||"units provisional"}`}catch{scene=demo;document.querySelector("#status").textContent="Preview geometry · CF4 data not built yet";document.querySelector("#scale").textContent="Supergalactic · demonstration only"}}load();
canvas.onpointerdown=e=>{drag=[e.clientX,e.clientY];canvas.setPointerCapture(e.pointerId)};canvas.onpointermove=e=>{if(!drag)return;yaw+=(e.clientX-drag[0])*.006;pitch=Math.max(-1.4,Math.min(1.4,pitch+(e.clientY-drag[1])*.006));drag=[e.clientX,e.clientY]};canvas.onpointerup=()=>drag=null;canvas.onwheel=e=>{zoom=Math.max(.3,Math.min(8,zoom*Math.exp(-e.deltaY*.001)))};
let pinch=null;canvas.addEventListener("touchmove",e=>{if(e.touches.length===2){const d=Math.hypot(e.touches[0].clientX-e.touches[1].clientX,e.touches[0].clientY-e.touches[1].clientY);if(pinch)zoom=Math.max(.3,Math.min(8,zoom*d/pinch));pinch=d}},{passive:true});canvas.addEventListener("touchend",()=>pinch=null);
for(const[id,key]of [["galaxies","G"],["flows","F"],["shells","S"],["axes","A"]])document.querySelector("#"+id).onclick=e=>{if(key==="G")showG=!showG;if(key==="F")showF=!showF;if(key==="A")showA=!showA;if(key==="S")showS=!showS;e.currentTarget.classList.toggle("on")};document.querySelector("#home").onclick=()=>{yaw=.55;pitch=.28;zoom=1.7};