import {transformCartesian} from "../../lib/coordinate-frames.mjs";
const canvas=document.querySelector("#sky"),ctx=canvas.getContext("2d",{alpha:false});let scene=null,showG=true,showF=false,showA=false;
let yaw=.55,pitch=.28,zoom=1.7,drag=null,showS=false,showV=false,showD=false,activeShell=300,displayFrame="galactic";
let velocitySamples=[],deepData=null,lrdData=null,lrdPopulation=null,showLRD=false,showDistant=false,deepMode=false,lrdHits=[],distantHits=[],selectedDeep=null;
function displayPosition(p){return transformCartesian(p,"supergalactic",displayFrame);}
const shellRadii=[50,100,160,200,300];
const anchors=[
 {id:"origin",label:"Milky Way / observer",position:[0,0,0],status:"reference"},
 {id:"laniakea",label:"Laniakea centre",position:[-47,13,-5],status:"published CF reconstruction",source:"Sorce et al. constrained Local Universe simulations"},
 {id:"great-attractor",label:"Great Attractor",position:[-40,5,0],status:"CF4/WALLABY reconstruction",source:"WALLABY pilot + CF4"},
 {id:"vela",label:"Vela",position:[-130,40,-140],status:"CF4/WALLABY reconstruction",source:"WALLABY pilot + CF4"}
];
const demo={coordinateFrame:{coordinates:"supergalactic",units:"Mpc/h"},layers:[{id:"galaxies",data:[]},{id:"streamlines",data:[]}]};
function resize(){const d=Math.min(devicePixelRatio||1,2);canvas.width=innerWidth*d;canvas.height=innerHeight*d;ctx.setTransform(d,0,0,d,0,0)}addEventListener("resize",resize);resize();
function project(p){let[x,y,z]=p;const cy=Math.cos(yaw),sy=Math.sin(yaw);[x,y]=[x*cy-y*sy,x*sy+y*cy];const cp=Math.cos(pitch),sp=Math.sin(pitch);[y,z]=[y*cp-z*sp,y*sp+z*cp];const s=Math.min(innerWidth,innerHeight)*.00145*zoom;return[innerWidth/2+x*s,innerHeight/2-z*s,y]}
function drawReferenceFrame(){if(!showA)return;
const frameLabels={
 galactic:[{p:[0,0,260],l:"Galactic North"},{p:[0,0,-260],l:"Galactic South"},{p:[260,0,0],l:"Galactic Centre"},{p:[-260,0,0],l:"Galactic Anticentre"},{p:[0,260,0],l:"l = 90°"},{p:[0,-260,0],l:"l = 270°"}],
 ecliptic:[{p:[0,0,260],l:"North Ecliptic Pole"},{p:[0,0,-260],l:"South Ecliptic Pole"},{p:[260,0,0],l:"Vernal Equinox · λ 0°"},{p:[-260,0,0],l:"λ 180°"},{p:[0,260,0],l:"λ 90°"},{p:[0,-260,0],l:"λ 270°"}],
 equatorial:[{p:[0,0,260],l:"North Celestial Pole"},{p:[0,0,-260],l:"South Celestial Pole"},{p:[260,0,0],l:"Vernal Equinox · RA 0h"},{p:[-260,0,0],l:"RA 12h"},{p:[0,260,0],l:"RA 6h"},{p:[0,-260,0],l:"RA 18h"}],
 supergalactic:[{p:[0,0,260],l:"SG North"},{p:[0,0,-260],l:"SG South"},{p:[260,0,0],l:"SGX +"},{p:[-260,0,0],l:"SGX −"},{p:[0,260,0],l:"SGY +"},{p:[0,-260,0],l:"SGY −"}]
};const refs=frameLabels[displayFrame]||frameLabels.galactic;/* display-reference orientation; catalogue transform follows */ const unused=[
 ];
 ctx.strokeStyle="#ffffff30";ctx.lineWidth=.7;
 for(const seg of [[[ -300,0,0],[300,0,0]],[[0,-300,0],[0,300,0]],[[0,0,-300],[0,0,300]]]){const a=project(displayPosition(seg[0])),b=project(displayPosition(seg[1]));ctx.beginPath();ctx.moveTo(a[0],a[1]);ctx.lineTo(b[0],b[1]);ctx.stroke()}
 ctx.fillStyle="#dbe6ff";ctx.font="10px system-ui";for(const r of refs){const q=project(displayPosition(r.p));ctx.fillText(r.l,q[0]+4,q[1])}}
function comovingDistanceMpc(z){if(!(z>0))return 0;const H0=67.4,Om=.315,Ol=.685,c=299792.458,n=160,h=z/n;let s=0;for(let i=0;i<=n;i++){const x=i*h,e=1/Math.sqrt(Om*Math.pow(1+x,3)+Ol);s+=(i===0||i===n?1:i%2?4:2)*e}return c/H0*h*s/3}
function deepRadiusFromZ(z){const d=comovingDistanceMpc(z);return 105+Math.min(205,d/10500*205)}
function deepPoint(o,r=null){if(o.ra_deg==null||o.dec_deg==null)return null;const rr=r??(o.z?deepRadiusFromZ(o.z):255),eq=lonLatToCartesianLocal(o.ra_deg,o.dec_deg,rr),p=displayFrame==="equatorial"?eq:transformCartesian(eq,"equatorial",displayFrame);return project(p)}
function lonLatToCartesianLocal(lon,lat,r=1){const L=lon*Math.PI/180,B=lat*Math.PI/180,c=Math.cos(B);return[r*c*Math.cos(L),r*c*Math.sin(L),r*Math.sin(B)]}
function drawDeepUniverse(){if(!deepMode||!deepData)return;ctx.font="10px system-ui";ctx.textBaseline="middle";
 if(showDistant){distantHits=[];for(const o of deepData.most_distant||[]){const q=deepPoint(o);if(!q)continue;ctx.fillStyle="#ffca78";ctx.beginPath();ctx.arc(q[0],q[1],3,0,Math.PI*2);ctx.fill();distantHits.push({x:q[0],y:q[1],o:{...o,z_type:"spectroscopic"}});}}
 if(showLRD){lrdHits=[];if(lrdPopulation){for(const a of lrdPopulation.objects||[]){const o={id:a[0],ra_deg:a[1],dec_deg:a[2],z_spec:a[3],z_phot:a[4],ref:a[5]};o.z=o.z_spec??o.z_phot;o.z_type=o.z_spec!=null?"spectroscopic":"photometric";const q=deepPoint(o);if(!q)continue;ctx.fillStyle=o.z_type==="spectroscopic"?"rgba(255,95,95,.78)":"rgba(255,80,125,.32)";ctx.beginPath();ctx.arc(q[0],q[1],o.z_type==="spectroscopic"?1.45:.85,0,Math.PI*2);ctx.fill();lrdHits.push({x:q[0],y:q[1],o});}}if(lrdData){for(const o of lrdData.objects||[]){const q=deepPoint(o);if(!q)continue;ctx.fillStyle="#ff2020";ctx.beginPath();ctx.arc(q[0],q[1],2.7,0,Math.PI*2);ctx.fill();}}ctx.fillStyle="#ff9b9b";ctx.font="10px system-ui";ctx.fillText("LRDs 919 · spec 115 · phot 855 · RUBIES 36",12,112);}
 if(selectedDeep){ctx.font="11px system-ui";ctx.fillStyle="#f4f6ff";const z=selectedDeep.z??selectedDeep.z_spec??selectedDeep.z_phot;const kind=selectedDeep.z_type==="photometric"?"phot-z":"spec-z";ctx.fillText(selectedDeep.id+" · "+kind+" "+Number(z).toFixed(3),12,132);}
}
function draw(){requestAnimationFrame(draw);ctx.fillStyle="#02040a";ctx.fillRect(0,0,innerWidth,innerHeight);if(!scene)return;const g=(scene.layers.find(x=>x.id==="galaxies")?.data||[]).filter(o=>Math.hypot(...o.position)<=activeShell),f=scene.layers.find(x=>x.id==="streamlines")?.data||[];
if(showS){ctx.strokeStyle="#ffffff18";ctx.lineWidth=.7;for(const r of shellRadii){ctx.beginPath();for(let i=0;i<=96;i++){const a=i/96*Math.PI*2,q=project(displayPosition([r*Math.cos(a),r*Math.sin(a),0]));i?ctx.lineTo(q[0],q[1]):ctx.moveTo(q[0],q[1])}ctx.stroke();const lab=project(displayPosition([r,0,0]));ctx.fillStyle="#ffffff55";ctx.font="9px system-ui";ctx.fillText(r+" h⁻¹ Mpc",lab[0]+3,lab[1]);}}
drawReferenceFrame();
if(showD){const dirs=[[0,-1,.35],[.15,-1,.25],[-.18,-1,.2]];ctx.lineWidth=1.2;dirs.forEach((d,i)=>{const a=project([0,0,0]),b=project(displayPosition(d.map(x=>x*180)));ctx.strokeStyle=["#ffffffaa","#ffffff66","#ffffff44"][i];ctx.beginPath();ctx.moveTo(a[0],a[1]);ctx.lineTo(b[0],b[1]);ctx.stroke()});}
if(showV&&velocitySamples.length){ctx.strokeStyle="#9fc2ff88";ctx.lineWidth=.7;for(const v of velocitySamples){const r=Math.hypot(...v.position);if(r>activeShell)continue;const vp=displayPosition(v.position),a=project(vp),m=Math.hypot(...v.velocity);if(!m)continue;const k=Math.min(18,m/70);const end=[v.position[0]+v.velocity[0]/m*k,v.position[1]+v.velocity[1]/m*k,v.position[2]+v.velocity[2]/m*k],b=project(displayPosition(end));ctx.beginPath();ctx.moveTo(a[0],a[1]);ctx.lineTo(b[0],b[1]);ctx.stroke();}}
if(showF){ctx.strokeStyle="#7aa7ff26";ctx.lineWidth=.55;for(const l of f){ctx.beginPath();l.points.forEach((p,i)=>{const q=project(displayPosition(p));i?ctx.lineTo(q[0],q[1]):ctx.moveTo(q[0],q[1])});ctx.stroke()}}
if(showG){for(const o of g){const q=project(displayPosition(o.position));const alpha=Math.max(.18,1-Math.abs(q[2])/700);ctx.fillStyle=`rgba(225,235,255,${alpha})`;ctx.fillRect(q[0],q[1],1.35,1.35)}}
drawDeepUniverse();ctx.font="11px system-ui";ctx.textBaseline="middle";for(const a of (deepMode?[]:anchors)){const q=project(displayPosition(a.position));ctx.fillStyle="#fff";ctx.beginPath();ctx.arc(q[0],q[1],a.id==="origin"?3:2,0,Math.PI*2);ctx.fill();ctx.fillStyle="#d9e5ff";ctx.fillText(a.label,q[0]+6,q[1]);}
}requestAnimationFrame(draw);
async function load(){try{const r=await fetch("../data/cf4/scene-mobile.json",{cache:"no-store"});if(!r.ok)throw 0;scene=await r.json();try{const vr=await fetch("../data/cf4/velocity-samples.json",{cache:"no-store"});if(vr.ok){const vd=await vr.json();velocitySamples=(vd.objects||[]).filter((_,i)=>i%Math.max(1,Math.ceil((vd.objects||[]).length/800))===0)}}catch{}document.querySelector("#status").textContent=(scene.review?"REVIEW FIXTURE · ":"")+(((scene.layers[0].data?.length??0)===0)?"synthetic galaxies removed":((scene.layers[0].data?.length??scene.layers[0].count??0).toLocaleString()+" galaxies"))+" · "+((scene.layers[1].data?.length??scene.layers[1].count??0).toLocaleString())+" review flows";document.querySelector("#scale").textContent="Supergalactic · "+(scene.coordinateFrame?.units||"units provisional")}catch{scene=demo;document.querySelector("#status").textContent="Preview geometry · CF4 data not built yet";document.querySelector("#scale").textContent="Supergalactic · demonstration only"}}load();
canvas.onpointerdown=e=>{drag=[e.clientX,e.clientY];canvas.setPointerCapture(e.pointerId)};canvas.onpointermove=e=>{if(!drag)return;yaw+=(e.clientX-drag[0])*.006;pitch=Math.max(-1.4,Math.min(1.4,pitch+(e.clientY-drag[1])*.006));drag=[e.clientX,e.clientY]};canvas.onpointerup=()=>drag=null;canvas.onwheel=e=>{zoom=Math.max(.3,Math.min(8,zoom*Math.exp(-e.deltaY*.001)))};
let pinch=null;canvas.addEventListener("touchmove",e=>{if(e.touches.length===2){const d=Math.hypot(e.touches[0].clientX-e.touches[1].clientX,e.touches[0].clientY-e.touches[1].clientY);if(pinch)zoom=Math.max(.3,Math.min(8,zoom*d/pinch));pinch=d}},{passive:true});canvas.addEventListener("touchend",()=>pinch=null);
for(const[id,key]of [["galaxies","G"],["flows","F"],["vectors","V"],["shells","S"],["axes","A"],["dipoles","D"]])document.querySelector("#"+id).onclick=e=>{if(key==="G")showG=!showG;if(key==="F")showF=!showF;if(key==="A")showA=!showA;if(key==="S")showS=!showS;if(key==="V")showV=!showV;if(key==="D")showD=!showD;e.currentTarget.classList.toggle("on")};document.querySelector("#home").onclick=()=>{yaw=.55;pitch=.28;zoom=1.7};
function updateContextButtons(v){const dawn=v==="cosmic-dawn",a=document.querySelector("#lrd"),b=document.querySelector("#distant");a.textContent=dawn?"Little Red Dots":"Nuclides";b.textContent=dawn?"Most Distant":"History Globe";a.classList.toggle("on",dawn&&showLRD);b.classList.toggle("on",dawn&&showDistant);if(!dawn){showLRD=false;showDistant=false;selectedDeep=null;}}
document.querySelector("#shell").onchange=e=>{const v=e.target.value;deepMode=v.startsWith("deep")||v==="cosmic-dawn";if(deepMode){showS=false;activeShell=300;zoom=v==="cosmic-dawn"?1.05:1.25;document.querySelector("#scale").textContent=e.target.options[e.target.selectedIndex].text+" · cosmological review domain";}else{activeShell=Number(v);zoom=Math.max(.75,Math.min(6,510/activeShell));showS=true;document.querySelector("#scale").textContent="Local Universe · "+v+" h⁻¹ Mpc";}document.querySelector("#shells").classList.toggle("on",!deepMode);updateContextButtons(v)};

document.querySelector("#lrd").onclick=e=>{if(document.querySelector("#shell").value!=="cosmic-dawn"){document.querySelector("#scale").textContent="Nuclides · Atlas route pending";return}showLRD=!showLRD;e.currentTarget.classList.toggle("on",showLRD)};
document.querySelector("#distant").onclick=e=>{if(document.querySelector("#shell").value!=="cosmic-dawn"){document.querySelector("#scale").textContent="History Globe · replacement route pending";return}showDistant=!showDistant;e.currentTarget.classList.toggle("on",showDistant)};
updateContextButtons(document.querySelector("#shell").value);
fetch("../data/deep-universe/review-seed.json",{cache:"no-store"}).then(r=>r.json()).then(d=>deepData=d).catch(()=>{});
fetch("../data/deep-universe/rubies-lrds.json",{cache:"no-store"}).then(r=>r.json()).then(d=>lrdData=d).catch(()=>{});
fetch("../data/deep-universe/lrd-catalogue-919.json",{cache:"no-store"}).then(r=>r.json()).then(d=>lrdPopulation=d).catch(()=>{});
canvas.addEventListener("click",e=>{if(!deepMode)return;const r=canvas.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top;let hit=null,best=14;for(const h of [...lrdHits,...distantHits]){const d=Math.hypot(h.x-x,h.y-y);if(d<best){best=d;hit=h}}selectedDeep=hit?.o||null;});
document.querySelector("#frame").onchange=e=>{displayFrame=e.target.value;showA=true;document.querySelector("#axes").classList.add("on");document.querySelector("#scale").textContent=e.target.options[e.target.selectedIndex].text+" reference · CF4 data native Supergalactic"};
